"""
Pre-campaign verification gates for the Python link-level simulator.

Purpose
-------
This module executes four deterministic checks before a simulation campaign is
allowed to run.  A failed gate raises RuntimeError immediately (assert is
not used, since assertions are removed under python -O), preventing
BER, BLER, EVM, or capacity results from being generated by an unverified
processing chain.

Verification gates
------------------
Gate 1: Constellation normalization
    Confirms unit average power for QPSK, 16-QAM, 64-QAM, and 256-QAM.

Gate 2: Noiseless modulation round trip
    Confirms that modulation followed by hard demodulation recovers every test
    bit exactly.

Gate 3: OFDM round trip
    Confirms machine-precision reconstruction after OFDM modulation and
    demodulation.

Gate 4: CRC24A integrity
    Confirms acceptance of a valid CRC block and rejection after one bit is
    deliberately corrupted.
"""


import numpy as np


from qam import qam_demodulate_hard, qam_modulate


from ofdm import ofdm_demodulate, ofdm_modulate


from crc24a import append_crc24a, check_crc24a


_SUPPORTED_MODULATIONS = (
    ("QPSK", 2),
    ("16QAM", 4),
    ("64QAM", 6),
    ("256QAM", 8),
)


def run_verification_gates(cfg, rng) -> None:
    """Execute all verification gates and raise on the first failure.

    Parameters
    ----------
    cfg : configuration object
        Must provide the OFDM dimensions and CRC configuration required by the
        imported processing functions.
    rng : numpy.random.Generator
        Seeded random-number generator used to keep the tests reproducible.

    Returns
    -------
    None
        Successful completion means that all four gates passed.
    """


    print("--- Verification gates ---")


    for modulation, bits_per_symbol in _SUPPORTED_MODULATIONS:

        constellation_size = 2**bits_per_symbol


        exhaustive_bits = np.array(
            [
                [
                    (symbol_index >> (bits_per_symbol - 1 - bit_index)) & 1
                    for bit_index in range(bits_per_symbol)
                ]
                for symbol_index in range(constellation_size)
            ],
            dtype=np.uint8,
        ).ravel()


        constellation = qam_modulate(
            exhaustive_bits,
            modulation,
        )


        average_power = np.mean(np.abs(constellation) ** 2)


        if not abs(average_power - 1.0) < 1e-12:
            raise RuntimeError(
            f"Gate 1 FAILED: {modulation} power "
            f"{average_power:.3e}"
        )


    print(
        "Gate 1 PASS: constellation power = 1 for all orders"
    )


    for modulation, bits_per_symbol in _SUPPORTED_MODULATIONS:


        transmitted_bits = rng.integers(
            0,
            2,
            120 * bits_per_symbol,
            dtype=np.uint8,
        )


        recovered_bits = qam_demodulate_hard(
            qam_modulate(transmitted_bits, modulation),
            modulation,
        )


        if not np.array_equal(transmitted_bits, recovered_bits):
            raise RuntimeError(
            f"Gate 2 FAILED: {modulation} round trip"
        )


    print("Gate 2 PASS: noiseless modulation round trip error-free")


    test_grid = (
        rng.standard_normal(
            (cfg.n_fft, cfg.n_symbols, cfg.n_tx)
        )
        + 1j
        * rng.standard_normal(
            (cfg.n_fft, cfg.n_symbols, cfg.n_tx)
        )
    ) / np.sqrt(2)


    reconstructed_grid = ofdm_demodulate(
        ofdm_modulate(test_grid, cfg),
        cfg,
        cfg.n_tx,
    )


    maximum_error = np.max(
        np.abs(test_grid - reconstructed_grid)
    )


    if not maximum_error < 1e-12:
        raise RuntimeError(
        "Gate 3 FAILED: OFDM round-trip error "
        f"{maximum_error:.3e}"
    )


    print(
        "Gate 3 PASS: OFDM round-trip error "
        f"{maximum_error:.2e}"
    )


    payload = rng.integers(
        0,
        2,
        200,
        dtype=np.uint8,
    )


    valid_block = append_crc24a(payload, cfg)


    if not check_crc24a(valid_block, cfg):
        raise RuntimeError(
        "Gate 4 FAILED: valid CRC rejected"
    )


    corrupted_block = valid_block.copy()


    corrupted_block[16] ^= 1


    if check_crc24a(corrupted_block, cfg):
        raise RuntimeError(
        "Gate 4 FAILED: corrupted CRC accepted"
    )


    print(
        "Gate 4 PASS: CRC24A accepts valid and rejects corrupted blocks"
    )


    print("--- All gates passed; campaign may run ---\n")
