
%% Simulink Testbench Builder:
%%
%{
The build_nr_pdsch_simulink script constructs the Simulink testbench of the PDSCH-oriented Massive MIMO-OFDM
link-level simulator, mirroring the verified processing chain from transport block to CRC decision of the MATLAB main
script. It is run once from the folder that contains the simulator source files. The script writes seven thin wrapper
functions, the sl-prefixed files, that connect the Simulink blocks to the existing verified functions, keeping any
wrapper file that already exists, and then programmatically draws, wires, configures, saves, and opens the model
NR_PDSCH_LinkLevel_Sim.slx.

The model executes one Monte Carlo frame per simulation step at a fixed step of one. The transmitter area hosts the
PDSCH Transmitter block on build_frame. The channel area hosts the MIMO Channel Generator on generate_channel, the
Wideband SVD Precoder on compute_precoder, and the Channel plus AWGN block on apply_mimo_channel. The receiver area
hosts the LS Channel Estimator on estimate_effective_channel_ls and the ZF-MMSE Equalizer on equalize_mimo. The metric
area hosts the Demap Descramble CRC Metrics block on compute_frame_metrics, the per-frame displays, the workspace
logs, and the cumulative BER path.

The verification gates execute in the model InitFcn before the first step, exactly as in the main script, so no
result can be produced on an unverified chain. The SNR is a Constant block with a default of twenty decibels; the
equalizer, the channel model, and every other parameter follow config.m, the single source of the locked
configuration. Forty frames reproduce one SNR point of the executed simulation, and the StopFcn prints the aggregated
BER, BLER, EVM, NMSE, and capacity.

Auxiliary functions:

    config
        Locked simulation configuration providing every model dimension and parameter.

    build_frame
        Deterministic layout probe fixing the signal dimensions of the model.

Input:

    Simulator source files        The verified MATLAB chain in the current folder.

Output:

    sl_*.m wrapper files          Thin wrappers connecting the blocks to the verified chain, written if missing.
    NR_PDSCH_LinkLevel_Sim.slx    Complete wired and configured testbench model, saved and opened.
%}


%% Locked configuration and derived dimensions:
%%

clear; clc;
addpath(genpath(pwd));                             % Add the project directory and all subdirectories to the MATLAB path.
cfg = config();                                    % Load the locked simulation configuration.
s0 = rng; frame0 = build_frame(cfg); rng(s0);      % Deterministic layout probe with the random state restored.
nSym  = cfg.nSymbols;  nSC = cfg.nSC;              % Grid dimensions of the model signals.
nTx   = cfg.nTx;       nRx = cfg.nRx;   nL = cfg.nLayers;      % Antenna and layer dimensions.
nData = size(frame0.dataPositions,1);              % Data resource elements per slot.
nBitsCrc = length(frame0.bitsCrc);                 % Payload plus CRC24A bits per frame.
fprintf('Configuration: %dx%d, L = %d, %s, %d data REs, %d CRC-attached bits\n', ...
    nTx, nRx, nL, upper(cfg.modulation), nData, nBitsCrc);

%% Wrapper functions connecting Simulink blocks to the verified chain:
%%

wrappers = { ...
'sl_layout.m', sprintf([ ...
'function [dmrsMask, dmrsValues, dataPositions] = sl_layout()\n' ...
'%% Deterministic frame layout (DM-RS mask, Gold-seeded pilot values, data\n' ...
'%% positions) shared by the receiver blocks. The layout of build_frame is\n' ...
'%% independent of the random payload, so the RNG state is snapshotted and\n' ...
'%% restored around the probe call to keep the Monte Carlo stream intact.\n' ...
'cfg = config();\n' ...
's = rng; f = build_frame(cfg); rng(s);\n' ...
'dmrsMask = f.dmrsMask; dmrsValues = f.dmrsValues; dataPositions = f.dataPositions;\n' ...
'end\n']), ...
'sl_transmitter.m', sprintf([ ...
'function [layerGrid, bitsCrc] = sl_transmitter(~)\n' ...
'%% One PDSCH frame per step: transport block, CRC24A, Gold scrambling,\n' ...
'%% unit-power Gray QAM, layer mapping, and DM-RS insertion (build_frame).\n' ...
'cfg = config();\n' ...
'f = build_frame(cfg);\n' ...
'layerGrid = f.layerGrid;\n' ...
'bitsCrc = double(f.bitsCrc);\n' ...
'end\n']), ...
'sl_channel.m', sprintf([ ...
'function H = sl_channel(~)\n' ...
'%% One independent channel realization per step (generate_channel):\n' ...
'%% AWGN, flat/iid Rayleigh, Rician, or TDL per config.m.\n' ...
'cfg = config();\n' ...
'H = generate_channel(cfg);\n' ...
'end\n']), ...
'sl_precoder.m', sprintf([ ...
'function W = sl_precoder(H)\n' ...
'%% Wideband SVD eigenbeamforming precoder (compute_precoder).\n' ...
'cfg = config();\n' ...
'W = compute_precoder(cfg, H);\n' ...
'end\n']), ...
'sl_apply_channel.m', sprintf([ ...
'function [rxGrid, noiseVar] = sl_apply_channel(layerGrid, H, W, snrDb)\n' ...
'%% Effective channel and receiver noise, y = HWs + n, at the\n' ...
'%% fixed total-transmit-SNR convention (apply_mimo_channel).\n' ...
'[rxGrid, noiseVar] = apply_mimo_channel(layerGrid, H, W, snrDb);\n' ...
'end\n']), ...
'sl_estimator.m', sprintf([ ...
'function Ghat = sl_estimator(rxGrid)\n' ...
'%% LS estimation on the DM-RS: time averaging over the DM-RS\n' ...
'%% symbols and linear frequency interpolation (estimate_effective_channel_ls).\n' ...
'cfg = config();\n' ...
'[dmrsMask, dmrsValues, ~] = sl_layout();\n' ...
'f.dmrsMask = dmrsMask; f.dmrsValues = dmrsValues;\n' ...
'Ghat = estimate_effective_channel_ls(rxGrid, f, cfg);\n' ...
'end\n']), ...
'sl_equalizer.m', sprintf([ ...
'function shat = sl_equalizer(rxGrid, Ghat, noiseVar)\n' ...
'%% ZF or unbiased MMSE per config.m (equalize_mimo).\n' ...
'cfg = config();\n' ...
'[~, ~, dataPositions] = sl_layout();\n' ...
'shat = equalize_mimo(rxGrid, Ghat, dataPositions, noiseVar, cfg);\n' ...
'end\n']), ...
'sl_metrics.m', sprintf([ ...
'function [bitErrors, nBits, blockError, evm, nmse, capacity] = sl_metrics(shat, layerGrid, bitsCrc, Ghat, H, W, snrDb)\n' ...
'%% Demapping, descrambling, CRC decision, and the simulator metric set.\n' ...
'cfg = config();\n' ...
'[~, ~, dataPositions] = sl_layout();\n' ...
'f.bitsCrc = uint8(bitsCrc(:));\n' ...
'f.payload = uint8(bitsCrc(1:end-cfg.crcLen));\n' ...
'f.layerGrid = layerGrid;\n' ...
'f.dataPositions = dataPositions;\n' ...
'met = compute_frame_metrics(shat, f, Ghat, H, W, snrDb, cfg);\n' ...
'bitErrors = met.bitErrors; nBits = met.nBits; blockError = met.blockError;\n' ...
'evm = met.evm; nmse = met.nmse; capacity = met.capacityBpsHz;\n' ...
'end\n'])};
for i = 1:2:numel(wrappers)
    if exist(wrappers{i}, 'file')
        fprintf('Kept existing %s\n', wrappers{i});   % Formatted wrapper files are preserved.
        continue
    end
    fid = fopen(wrappers{i}, 'w'); fprintf(fid, '%s', wrappers{i+1}); fclose(fid);
    fprintf('Wrote %s\n', wrappers{i});
end

%% Model shell:
%%

mdl = 'NR_PDSCH_LinkLevel_Sim';                    % Testbench model name.
if bdIsLoaded(mdl); close_system(mdl, 0); end      % Close a loaded copy without saving.
if exist([mdl '.slx'], 'file'); delete([mdl '.slx']); end     % Rebuild from a clean file.
new_system(mdl); open_system(mdl);                 % Fresh model shell in the editor.
set_param(mdl, 'SolverType', 'Fixed-step', 'Solver', 'FixedStepDiscrete', ...     % One frame per fixed step;
    'FixedStep', '1', 'StopTime', num2str(cfg.numFrames - 1), ...                 % forty steps reproduce one
    'ReturnWorkspaceOutputs', 'off');                                              % SNR point of the sweep.
set_param(mdl, 'InitFcn', sprintf([ ...            % Gates run before the first step, as in the main script.
    'addpath(genpath(pwd));\ncfg = config();\nrng(cfg.randomSeed);\n' ...
    'run_verification_gates(cfg);   %% gates before results']));
set_param(mdl, 'StopFcn', sprintf([ ...            % Aggregate printout after the final step.
    'ber = sum(log_bitErrors)/sum(log_nBits);\n' ...
    'bler = mean(log_blockError);\n' ...
    'fprintf(''\\n=== Simulink run aggregate (one SNR point) ===\\n'');\n' ...
    'fprintf(''BER  = %%.5g\\nBLER = %%.4g\\nEVM  = %%.4g %%%%\\nNMSE = %%.5g\\nCapacity = %%.4g bit/s/Hz\\n'', ...\n' ...
    '    ber, bler, 100*mean(log_evm), mean(log_nmse), mean(log_capacity));']));

%% Helper for MATLAB Function block scripts (thin, fixed-size, extrinsic):
%%

mfScript = containers.Map();                       % Block scripts keyed by block name.
mfScript('PDSCH Transmitter') = sprintf([ ...
'function [layerGrid, bitsCrc] = fcn(tick) %%#ok<INUSD>\n' ...
'%% build_frame: TB -> CRC24A -> Gold scrambling -> QAM -> layers + DM-RS\n' ...
'coder.extrinsic(''sl_transmitter'');\n' ...
'layerGrid = complex(zeros(%d,%d,%d));\n' ...
'bitsCrc = zeros(%d,1);\n' ...
'[layerGrid, bitsCrc] = sl_transmitter(tick);\n'], nSym, nSC, nL, nBitsCrc);
mfScript('MIMO Channel Generator') = sprintf([ ...
'function H = fcn(tick) %%#ok<INUSD>\n' ...
'%% generate_channel: one realization per frame (AWGN/Rayleigh/Rician/TDL)\n' ...
'coder.extrinsic(''sl_channel'');\n' ...
'H = complex(zeros(%d,%d,%d));\n' ...
'H = sl_channel(tick);\n'], nSC, nRx, nTx);
mfScript('Wideband SVD Precoder') = sprintf([ ...
'function W = fcn(H)\n' ...
'%% compute_precoder: wideband eigenbeamforming\n' ...
'coder.extrinsic(''sl_precoder'');\n' ...
'W = complex(zeros(%d,%d));\n' ...
'W = sl_precoder(H);\n'], nTx, nL);
mfScript('MIMO Channel + AWGN') = sprintf([ ...
'function [rxGrid, noiseVar] = fcn(layerGrid, H, W, snrDb)\n' ...
'%% apply_mimo_channel: y = HWs + n, total-transmit-SNR noise\n' ...
'coder.extrinsic(''sl_apply_channel'');\n' ...
'rxGrid = complex(zeros(%d,%d,%d));\n' ...
'noiseVar = 0;\n' ...
'[rxGrid, noiseVar] = sl_apply_channel(layerGrid, H, W, snrDb);\n'], nSym, nSC, nRx);
mfScript('LS Channel Estimator') = sprintf([ ...
'function Ghat = fcn(rxGrid)\n' ...
'%% estimate_effective_channel_ls: LS on DM-RS\n' ...
'coder.extrinsic(''sl_estimator'');\n' ...
'Ghat = complex(zeros(%d,%d,%d));\n' ...
'Ghat = sl_estimator(rxGrid);\n'], nSC, nRx, nL);
mfScript('ZF-MMSE Equalizer') = sprintf([ ...
'function shat = fcn(rxGrid, Ghat, noiseVar)\n' ...
'%% equalize_mimo: ZF or unbiased MMSE, per config.m\n' ...
'coder.extrinsic(''sl_equalizer'');\n' ...
'shat = complex(zeros(%d,%d));\n' ...
'shat = sl_equalizer(rxGrid, Ghat, noiseVar);\n'], nData, nL);
mfScript('Demap Descramble CRC Metrics') = sprintf([ ...
'function [bitErrors, nBits, blockError, evm, nmse, capacity] = fcn(shat, layerGrid, bitsCrc, Ghat, H, W, snrDb)\n' ...
'%% compute_frame_metrics: BER, BLER, EVM, NMSE, and layer capacity\n' ...
'coder.extrinsic(''sl_metrics'');\n' ...
'bitErrors = 0; nBits = 0; blockError = 0; evm = 0; nmse = 0; capacity = 0;\n' ...
'[bitErrors, nBits, blockError, evm, nmse, capacity] = sl_metrics(shat, layerGrid, bitsCrc, Ghat, H, W, snrDb);\n']);

%% Blocks (positions laid out left to right: TX | CHANNEL | RX | METRICS):
%%

addMF = @(name, pos) add_block('simulink/User-Defined Functions/MATLAB Function', [mdl '/' name], 'Position', pos);   % MATLAB Function block helper.
addMF('PDSCH Transmitter',            [140 150 320 230]);
addMF('MIMO Channel Generator',       [140 330 320 400]);
addMF('Wideband SVD Precoder',        [400 330 560 400]);
addMF('MIMO Channel + AWGN',          [640 140 820 260]);
addMF('LS Channel Estimator',         [900 300 1070 360]);
addMF('ZF-MMSE Equalizer',            [1150 150 1320 250]);
addMF('Demap Descramble CRC Metrics', [1420 140 1650 330]);

add_block('simulink/Sources/Digital Clock', [mdl '/Frame Clock'], ...       % Step index driving the frame sources.
    'Position', [30 200 90 230], 'SampleTime', '1');
add_block('simulink/Sources/Constant', [mdl '/SNR (dB)'], ...               % Operating-point constant of the run.
    'Position', [400 450 480 480], 'Value', '20', 'SampleTime', '1');
add_block('simulink/Signal Routing/Goto', [mdl '/Goto SNR'], 'Position', [520 450 600 480], 'GotoTag', 'SNR');
add_block('simulink/Signal Routing/From', [mdl '/From SNR ch'], 'Position', [540 232 620 258], 'GotoTag', 'SNR');
add_block('simulink/Signal Routing/From', [mdl '/From SNR met'], 'Position', [1300 302 1380 328], 'GotoTag', 'SNR');

%% Metric sinks: displays, logging, and the cumulative BER path:
%%

addDisp = @(name, pos) add_block('simulink/Sinks/Display', [mdl '/' name], 'Position', pos);   % Display sink helper.
addDisp('BLER frame', [1740 205 1830 235]);
addDisp('EVM',        [1740 250 1830 280]);
addDisp('NMSE',       [1740 295 1830 325]);
addDisp('Capacity',   [1740 340 1830 370]);
addTW = @(name, vname, pos) add_block('simulink/Sinks/To Workspace', [mdl '/' name], ...       % Workspace log helper.
    'Position', pos, 'VariableName', vname, 'SaveFormat', 'Array');
addTW('Log bitErrors',  'log_bitErrors',  [1900 120 2010 150]);
addTW('Log nBits',      'log_nBits',      [1900 165 2010 195]);
addTW('Log blockError', 'log_blockError', [1900 210 2010 240]);
addTW('Log EVM',        'log_evm',        [1900 255 2010 285]);
addTW('Log NMSE',       'log_nmse',       [1900 300 2010 330]);
addTW('Log capacity',   'log_capacity',   [1900 345 2010 375]);

add_block('simulink/Discrete/Discrete-Time Integrator', [mdl '/Sum bit errors'], ...   % Running bit-error sum.
    'Position', [1740 60 1790 90], 'SampleTime', '1');
add_block('simulink/Discrete/Discrete-Time Integrator', [mdl '/Sum bits'], ...         % Running bit-count sum.
    'Position', [1740 110 1790 140], 'SampleTime', '1', 'InitialCondition', '1');
    % InitialCondition 1 keeps the BER divider defined at the first step;
    % against roughly 6e5 accumulated bits the bias is below 1e-5 relative.
add_block('simulink/Math Operations/Divide', [mdl '/BER ratio'], 'Position', [1830 75 1870 115]);   % Cumulative BER.
addDisp('Cumulative BER', [1900 75 2010 105]);

%% MATLAB Function block scripts (via the Stateflow API):
%%

rt = sfroot;                                       % Root object giving access to the block scripts.
names = keys(mfScript);                            % All MATLAB Function block names.
for i = 1:numel(names)
    ch = rt.find('-isa', 'Stateflow.EMChart', 'Path', [mdl '/' names{i}]);   % Script object of this block.
    ch.Script = mfScript(names{i});                % Thin fixed-size extrinsic script installed.
end

%% Wiring (autorouted):
%%

L = @(a,b) add_line(mdl, a, b, 'autorouting', 'on');           % Autorouted wiring helper.
L('Frame Clock/1', 'PDSCH Transmitter/1');
L('Frame Clock/1', 'MIMO Channel Generator/1');
L('SNR (dB)/1', 'Goto SNR/1');
L('PDSCH Transmitter/1', 'MIMO Channel + AWGN/1');           % layerGrid
L('MIMO Channel Generator/1', 'Wideband SVD Precoder/1');    % H -> precoder
L('MIMO Channel Generator/1', 'MIMO Channel + AWGN/2');      % H
L('Wideband SVD Precoder/1', 'MIMO Channel + AWGN/3');       % W
L('From SNR ch/1', 'MIMO Channel + AWGN/4');                 % SNR
L('MIMO Channel + AWGN/1', 'LS Channel Estimator/1');        % rxGrid
L('MIMO Channel + AWGN/1', 'ZF-MMSE Equalizer/1');           % rxGrid
L('LS Channel Estimator/1', 'ZF-MMSE Equalizer/2');          % Ghat
L('MIMO Channel + AWGN/2', 'ZF-MMSE Equalizer/3');           % noiseVar
L('ZF-MMSE Equalizer/1', 'Demap Descramble CRC Metrics/1');  % shat
L('PDSCH Transmitter/1', 'Demap Descramble CRC Metrics/2');  % layerGrid (reference)
L('PDSCH Transmitter/2', 'Demap Descramble CRC Metrics/3');  % bitsCrc (reference)
L('LS Channel Estimator/1', 'Demap Descramble CRC Metrics/4'); % Ghat
L('MIMO Channel Generator/1', 'Demap Descramble CRC Metrics/5'); % H
L('Wideband SVD Precoder/1', 'Demap Descramble CRC Metrics/6');  % W
L('From SNR met/1', 'Demap Descramble CRC Metrics/7');           % SNR
L('Demap Descramble CRC Metrics/1', 'Sum bit errors/1');
L('Demap Descramble CRC Metrics/1', 'Log bitErrors/1');
L('Demap Descramble CRC Metrics/2', 'Sum bits/1');
L('Demap Descramble CRC Metrics/2', 'Log nBits/1');
L('Sum bit errors/1', 'BER ratio/1');
L('Sum bits/1', 'BER ratio/2');
L('BER ratio/1', 'Cumulative BER/1');
L('Demap Descramble CRC Metrics/3', 'BLER frame/1');
L('Demap Descramble CRC Metrics/3', 'Log blockError/1');
L('Demap Descramble CRC Metrics/4', 'EVM/1');
L('Demap Descramble CRC Metrics/4', 'Log EVM/1');
L('Demap Descramble CRC Metrics/5', 'NMSE/1');
L('Demap Descramble CRC Metrics/5', 'Log NMSE/1');
L('Demap Descramble CRC Metrics/6', 'Capacity/1');
L('Demap Descramble CRC Metrics/6', 'Log capacity/1');

%% Area labels and title, matching the testbench style:
%%

labels = { ...
    sprintf('5G NR PDSCH %dx%d MIMO-OFDM Link-Level Testbench', nTx, nRx), [520 20], 18; ...   % Dimension-derived
                                                   % title, so the compact and massive benches identify themselves.
    'TRANSMITTER',         [160 110], 12; ...
    'WIRELESS CHANNEL',    [620 110], 12; ...
    'RECEIVER',            [1150 110], 12; ...
    'METRICS AND LOGGING', [1460 110], 12};
for i = 1:size(labels,1)
    try
        a = Simulink.Annotation(mdl, labels{i,1});           % R2018a+ syntax
    catch
        a = Simulink.Annotation([mdl '/' labels{i,1}]);      % legacy path syntax
    end
    p = labels{i,2};
    try
        a.Position = p;                                      % [x y] in newer releases
    catch
        a.Position = [p(1) p(2) p(1)+420 p(2)+26];           % [l t r b] in older releases
    end
    a.FontSize = labels{i,3};
    a.FontWeight = 'bold';
end

%% Save and open:
%%

save_system(mdl);                                  % Save the completed model.
open_system(mdl);                                  % Open it in the editor.
fprintf('\nModel %s.slx created.\n', mdl);
fprintf('Run it with the green Run button, or:  sim(''%s'')\n', mdl);
fprintf('SNR point: edit the "SNR (dB)" Constant block. Equalizer/channel: edit config.m.\n');

%% Compiler check:
%%

% A C compiler is optional here: every block runs the .m files interpreted.
try
    cc = mex.getCompilerConfigurations('C', 'Selected');
    if isempty(cc)
        fprintf('Note: no C compiler selected; the model runs interpreted and results are unaffected.\n');
    end
catch
end



